# Generated by Django 5.1.2 on 2024-11-07 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('medical_record', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('equipo_medico', 'Equipo Médico'), ('cama', 'Cama'), ('ventilador', 'Ventilador'), ('monitor', 'Monitor'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.RemoveField(
            model_name='resource',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='code',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='resourceoperationlog',
            name='details',
        ),
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resourceoperationlog',
            name='operation_type',
            field=models.CharField(choices=[('creación', 'Creación'), ('asignación', 'Asignación'), ('liberación', 'Liberación'), ('modificación', 'Modificación')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resourceoperationlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ResourceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('emergencia', 'Emergencia')], max_length=20)),
                ('assignment_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.patient')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.resource')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ResourceType',
        ),
    ]
